apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: application-k8
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
        - name: mongo-express
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_SERVER
              value: "mongo"  # MongoDB service name
            - name: ME_CONFIG_MONGODB_PORT
              value: "27017"  # MongoDB port
            - name: ME_CONFIG_MONGODB_AUTH_DATABASE
              value: ""  # Disable auth by setting to empty string
            - name: ME_CONFIG_MONGODB_AUTH_USERNAME
              value: ""  # Disable auth by setting to empty string
            - name: ME_CONFIG_MONGODB_AUTH_PASSWORD
              value: ""  # Disable auth by setting to empty string
            - name: ME_CONFIG_SITE_BASEURL
              value: "/"
            - name: ME_CONFIG_SITE_ADMIN_USERNAME
              value: "admin"  # Admin username for Mongo Express (optional)
            - name: ME_CONFIG_SITE_ADMIN_PASSWORD
              value: ""  # Remove password prompt for admin user

---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: application-k8
spec:
  selector:
    app: mongo-express
  ports:
    - port: 8081
      targetPort: 8081
